stages:
    - build
    - deploy
maven-build:
    stage: build
    variables:
        SERVER_PASSWORD: $SERVER_PASSWORD
        SERVER_USERNAME: $SERVER_USERNAME
    script: "mvn package -B"
    artifacts:
        paths:
            - target/*.war
Deploy:
    stage: deploy
    variables:
        SERVER_PASSWORD: $SERVER_PASSWORD
        SERVER_USERNAME: $SERVER_USERNAME
    when: manual
    script:
        - scp -o StrictHostKeyChecking=no /home/gitlab-runner/builds/xEAPXJdS/0/Daniel-Mason/StarMap/target/ROOT.war hive:/home/orca/EDSM_APP/API_LAYER
        - 'cd /home/orca/EDSM_APP/API_LAYER'
        - 'sudo docker build -t StarMap_API'
        - 'sudo docker rm -v /StarMap_API_Container'
        - 'sudo docker run -p 8080:8080 -it --name StarMap_API_Container StarMap_API'