spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.orm.jpa: DEBUG
    StarMap: INFO
    hibernate: INFO
  file:
    logging.log

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:55320/StarMap
    username: ${STARMAP_USERNAME}
    password: ${STARMAP_PASSWORD}
    driver-class-name: org.postgresql.Driver

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://192.168.1.60:55320/EDSM
    username: ${SERVER_USERNAME}
    password: ${SERVER_PASSWORD}
    driver-class-name: org.postgresql.Driver